import type { NovaConfig } from "../config.js";
import type { ResolvedApp } from "../resolve.js";
import { Emitter } from "./emitter.js";
import { HEADER, type EmittedFile } from "./types.js";

export function emitRuntime(_app: ResolvedApp, _config: NovaConfig): EmittedFile {
  const e = new Emitter();
  e.lines([
    HEADER,
    '"use client";',
    "",
    'import * as React from "react";',
    "",
    "export type LoaderState<T> = { loading: boolean; error: string | null; value: T | null };",
    "",
    "/**",
    " * Fetch JSON, discarding responses that arrive after a newer request started.",
    " *",
    " * `Input` is the loader's own declared parameter type. The query object nova builds",
    " * from the page's route params and filter values must satisfy it, so a loader input",
    " * that no param or filter supplies is a compile error at the call site rather than a",
    " * request that fails at runtime. It defaults to `unknown` (which intersects away) for",
    " * a loader declared with no parameters at all.",
    " */",
    "export function useLoader<T, Input = unknown>(",
    "  path: string,",
    "  query: Record<string, string> & Input,",
    "): LoaderState<T> {",
    "  const [state, setState] = React.useState<LoaderState<T>>({",
    "    loading: true,",
    "    error: null,",
    "    value: null,",
    "  });",
    "  const seq = React.useRef(0);",
    "  const key = JSON.stringify(query);",
    "  React.useEffect(() => {",
    "    const mine = ++seq.current;",
    "    setState((s) => ({ ...s, loading: true, error: null }));",
    "    const url = path + (key === '{}' ? '' : '?' + new URLSearchParams({ ...query }).toString());",
    "    fetch(url, { headers: { accept: 'application/json' } })",
    "      .then(async (r) => {",
    "        if (!r.ok) throw new Error(`${r.status} ${r.statusText}`);",
    "        return (await r.json()) as T;",
    "      })",
    "      .then((value) => {",
    "        if (seq.current === mine) setState({ loading: false, error: null, value });",
    "      })",
    "      .catch((e: unknown) => {",
    "        if (seq.current === mine) {",
    "          setState({ loading: false, error: e instanceof Error ? e.message : String(e), value: null });",
    "        }",
    "      });",
    "  }, [path, key]);",
    "  return state;",
    "}",
    "",
    "/**",
    " * Filter values, kept in the query string so a refresh preserves them.",
    " *",
    " * Keyed by the filter names the caller declares, not by an open index signature, so",
    " * `filters.month` is a `string` — not `string | undefined` — on a host that turns on",
    " * `noUncheckedIndexedAccess`.",
    " */",
    "export function useFilters<K extends string>(",
    "  defaults: Record<K, string>,",
    "): Record<K, string> & { set(name: K, value: string): void } {",
    "  const read = React.useCallback((): Record<string, string> => {",
    "    const search = new URLSearchParams(window.location.search);",
    "    const out: Record<string, string> = { ...defaults };",
    "    for (const name of Object.keys(defaults)) {",
    "      const v = search.get(name);",
    "      if (v !== null) out[name] = v;",
    "    }",
    "    return out;",
    "  }, [JSON.stringify(defaults)]);",
    "",
    "  const [values, setValues] = React.useState(read);",
    "  React.useEffect(() => {",
    "    const onPop = () => setValues(read());",
    "    window.addEventListener('popstate', onPop);",
    "    return () => window.removeEventListener('popstate', onPop);",
    "  }, [read]);",
    "",
    "  const set = React.useCallback((name: K, value: string) => {",
    "    const search = new URLSearchParams(window.location.search);",
    "    search.set(name, value);",
    "    window.history.replaceState(null, '', `${window.location.pathname}?${search.toString()}`);",
    "    setValues((v) => ({ ...v, [name]: value }));",
    "  }, []);",
    "",
    "  return React.useMemo(",
    "    () => ({ ...values, set }) as unknown as Record<K, string> & { set(name: K, value: string): void },",
    "    [values, set],",
    "  );",
    "}",
    "",
    "export type ActionState = { busy: boolean; error: string | null; fieldErrors: Record<string, string> };",
    "",
    "/** Submit to an action endpoint, with optional confirmation and field errors. */",
    "export function useAction(",
    "  path: string,",
    "  opts: { confirm?: string } = {},",
    "): ActionState & { run(input: unknown): Promise<boolean> } {",
    "  const [state, setState] = React.useState<ActionState>({",
    "    busy: false,",
    "    error: null,",
    "    fieldErrors: {},",
    "  });",
    "  const run = React.useCallback(",
    "    async (input: unknown): Promise<boolean> => {",
    "      if (opts.confirm !== undefined && !window.confirm(opts.confirm)) return false;",
    "      setState({ busy: true, error: null, fieldErrors: {} });",
    "      try {",
    "        const r = await fetch(path, {",
    "          method: 'POST',",
    "          headers: { 'content-type': 'application/json' },",
    "          body: JSON.stringify(input),",
    "        });",
    "        const body = (await r.json()) as",
    "          | { ok: true }",
    "          | { ok: false; fieldErrors?: Record<string, string> };",
    "        if (!r.ok) throw new Error(`${r.status} ${r.statusText}`);",
    "        if (body.ok) {",
    "          setState({ busy: false, error: null, fieldErrors: {} });",
    "          return true;",
    "        }",
    "        setState({ busy: false, error: null, fieldErrors: body.fieldErrors ?? {} });",
    "        return false;",
    "      } catch (e: unknown) {",
    "        setState({",
    "          busy: false,",
    "          error: e instanceof Error ? e.message : String(e),",
    "          fieldErrors: {},",
    "        });",
    "        return false;",
    "      }",
    "    },",
    "    [path, opts.confirm],",
    "  );",
    "  return { ...state, run };",
    "}",
  ]);
  return { name: "runtime.tsx", text: e.text(), map: e.map() };
}
