import type { NovaConfig } from "../config.js";
import type { ResolvedApp } from "../resolve.js";
import { Emitter, type LineMap } from "./emitter.js";

export type EmittedFile = { name: string; text: string; map: LineMap };

export const HEADER = "// AUTO-GENERATED by Nova — do not edit.";

export const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

export const rel = (config: NovaConfig, path: string) => `${path}${config.importExtension ?? ""}`;

export function emitTypes(app: ResolvedApp, config: NovaConfig): EmittedFile {
  const e = new Emitter();
  e.line(HEADER).line();
  if (app.loaders.length > 0) e.line(`import type * as data from "${rel(config, "../data")}";`);
  if (app.actions.length > 0) e.line(`import type * as actions from "${rel(config, "../actions")}";`);
  if (app.computes.length > 0) e.line(`import type * as compute from "${rel(config, "../compute")}";`);
  e.line();
  for (const name of app.loaders) {
    e.line(`export type ${cap(name)} = Awaited<ReturnType<typeof data.${name}>>;`);
    e.line(`export type ${cap(name)}Input = Parameters<typeof data.${name}>[0];`);
  }
  for (const name of app.actions) {
    e.line(`export type ${cap(name)} = typeof actions.${name};`);
  }
  for (const name of app.computes) {
    e.line(`export type ${cap(name)} = typeof compute.${name};`);
  }
  return { name: "types.ts", text: e.text(), map: e.map() };
}
