import { relative, resolve, sep } from "node:path";
import type { NovaConfig } from "../config.js";
import type { ResolvedApp } from "../resolve.js";
import { Emitter, type LineMap } from "./emitter.js";

export type EmittedFile = { name: string; text: string; map: LineMap };

export const HEADER = "// AUTO-GENERATED by Nova — do not edit.";

export const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

export const rel = (config: NovaConfig, path: string) => `${path}${config.importExtension ?? ""}`;

/**
 * Specifier for a module that lives at the app root (`data.ts`, `actions.ts`,
 * `compute.ts`), as seen from the emitted output directory. `outDir` is one directory
 * name relative to the app root in the common case ("generated" → "../data"), but it may
 * be nested arbitrarily deep (e.g. "src/generated" → "../../data"), may escape the app
 * directory, and may be absolute — so the path back must be computed from the two
 * resolved directories rather than from `outDir`'s own text.
 *
 * It used to be `relative(config.outDir, ".")` — the app root approximated by
 * `process.cwd()`. The two coincide only for an `outDir` nested inside the app *and* a
 * build run from the app's parent, which is exactly the shape the reference consumer
 * had, so the bug stayed invisible until an absolute `outDir` emitted
 * `import ... from "../../../data"` at a directory that has no data.ts.
 *
 * Computed with `node:path.relative` — the same primitive `resolve.ts`'s
 * `specifierFromOutDir` uses for catalog/local-component specifiers — rather than by
 * hand-splitting `outDir` on "/". A hand-rolled split previously miscounted "."
 * segments (so `outDir: "./generated"`, an entirely ordinary value equivalent to
 * "generated", produced an extra "../"); `path.relative` normalises that away for
 * free, and keeps this computation from silently diverging from
 * `specifierFromOutDir`'s again.
 */
export function appRel(app: ResolvedApp, config: NovaConfig, name: string): string {
  const up =
    relative(resolve(app.appDir, config.outDir), app.appDir).split(sep).join("/") || ".";
  return rel(config, `${up}/${name}`);
}

export function emitTypes(app: ResolvedApp, config: NovaConfig): EmittedFile {
  const e = new Emitter();
  e.line(HEADER).line();
  if (app.loaders.length > 0) e.line(`import type * as data from "${appRel(app, config, "data")}";`);
  if (app.actions.length > 0) e.line(`import type * as actions from "${appRel(app, config, "actions")}";`);
  e.line();
  for (const name of app.loaders) {
    e.line(`export type ${cap(name)} = Awaited<ReturnType<typeof data.${name}>>;`);
    // Parameters<typeof data.x>[0] indexes into an empty tuple for a zero-parameter
    // loader — a TS error with no relation to anything the author wrote. A loader with
    // no inputs is a normal pattern, so it gets a plain empty-object Input type instead;
    // `data.x` is still assignable to `(input: Record<string, never>) => ...` in
    // __contract.ts because a zero-parameter function accepts being called with (and
    // ignores) any extra argument the caller's type signature offers.
    e.line(
      app.loaderArity[name] === 0
        ? `export type ${cap(name)}Input = Record<string, never>;`
        : `export type ${cap(name)}Input = Parameters<typeof data.${name}>[0];`,
    );
  }
  for (const name of app.actions) {
    // `${Cap}` is the action itself, and the only thing that names it is `useAction`'s
    // `Awaited<ReturnType<…>>` — the second type argument that carries the action's own
    // answer out to a component prop. A form reaches its action through
    // `useForm<${Cap}Input>` and never names the other half, so an action bound only by
    // a `submit:` got an alias no emitted file imported.
    if (app.propActions.includes(name)) {
      e.line(`export type ${cap(name)} = typeof actions.${name};`);
    }
    // Every action needs its *input* type, not only a form's. `useForm<XInput>` is what
    // makes each field's `name` a checked key of it, and `useAction<XInput>` is what
    // makes a prop-bound action's payload checked at all: `run` used to take `unknown`,
    // which every callback shape a component could declare accepted silently.
    e.line(
      app.actionArity[name] === 0
        ? `export type ${cap(name)}Input = Record<string, never>;`
        : `export type ${cap(name)}Input = Parameters<typeof actions.${name}>[0];`,
    );
  }
  // No type is emitted for a `compute#` binding. pages.tsx imports the compute module
  // itself and references the function directly, so a `typeof compute.x` alias here was
  // one line per binding, in every app, that no emitted file ever imported.
  return { name: "types.ts", text: e.text(), map: e.map() };
}
