import { relative, sep } from "node:path";
import type { NovaConfig } from "../config.js";
import type { ResolvedApp } from "../resolve.js";
import { Emitter, type LineMap } from "./emitter.js";

export type EmittedFile = { name: string; text: string; map: LineMap };

export const HEADER = "// AUTO-GENERATED by Nova — do not edit.";

export const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

export const rel = (config: NovaConfig, path: string) => `${path}${config.importExtension ?? ""}`;

/**
 * Specifier for a module that lives at the app root (`data.ts`, `actions.ts`,
 * `compute.ts`), as seen from the emitted output directory. `outDir` is one directory
 * name relative to the app root in the common case ("generated" → "../data"), but it may
 * be nested arbitrarily deep (e.g. "src/generated" → "../../data"), so the number of
 * "../" segments must track outDir's own depth rather than assume exactly one.
 *
 * Computed with `node:path.relative` — the same primitive `resolve.ts`'s
 * `specifierFromOutDir` uses for catalog/local-component specifiers — rather than by
 * hand-splitting `outDir` on "/". A hand-rolled split previously miscounted "."
 * segments (so `outDir: "./generated"`, an entirely ordinary value equivalent to
 * "generated", produced an extra "../"); `path.relative` normalises that away for
 * free, and keeps this computation from silently diverging from
 * `specifierFromOutDir`'s again.
 */
export function appRel(config: NovaConfig, name: string): string {
  const up = relative(config.outDir, ".").split(sep).join("/") || ".";
  return rel(config, `${up}/${name}`);
}

export function emitTypes(app: ResolvedApp, config: NovaConfig): EmittedFile {
  const e = new Emitter();
  e.line(HEADER).line();
  if (app.loaders.length > 0) e.line(`import type * as data from "${appRel(config, "data")}";`);
  if (app.actions.length > 0) e.line(`import type * as actions from "${appRel(config, "actions")}";`);
  if (app.computes.length > 0) e.line(`import type * as compute from "${appRel(config, "compute")}";`);
  e.line();
  for (const name of app.loaders) {
    e.line(`export type ${cap(name)} = Awaited<ReturnType<typeof data.${name}>>;`);
    // Parameters<typeof data.x>[0] indexes into an empty tuple for a zero-parameter
    // loader — a TS error with no relation to anything the author wrote. A loader with
    // no inputs is a normal pattern, so it gets a plain empty-object Input type instead;
    // `data.x` is still assignable to `(input: Record<string, never>) => ...` in
    // __contract.ts because a zero-parameter function accepts being called with (and
    // ignores) any extra argument the caller's type signature offers.
    e.line(
      app.loaderArity[name] === 0
        ? `export type ${cap(name)}Input = Record<string, never>;`
        : `export type ${cap(name)}Input = Parameters<typeof data.${name}>[0];`,
    );
  }
  for (const name of app.actions) {
    e.line(`export type ${cap(name)} = typeof actions.${name};`);
  }
  for (const name of app.computes) {
    e.line(`export type ${cap(name)} = typeof compute.${name};`);
  }
  return { name: "types.ts", text: e.text(), map: e.map() };
}
